apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-wy8d
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-wy8d
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-wy8d
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-wy8d
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-wy8d
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wlhx-tenant/rhtap-demo-app/hacbs-test-project-wy8d@sha256:99ef27b7462ec8f4aab3a302dac48668838fb1f2a3203114d4ef1367174d2452
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
